name: Test Secrets
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if BLOGGER_CLIENT_ID is set
        run: |
          if [ -z "${{ secrets.BLOGGER_CLIENT_ID }}" ]; then
            echo "BLOGGER_CLIENT_ID is not set"
            exit 1
          else
            echo "BLOGGER_CLIENT_ID is set"
          fi