name: MD2Blogger Reusable Workflow Caller

on:
  push:
    branches: [ main ]

jobs:
  call-md2blogger:
    uses: swellful-life/md2blogger/.github/workflows/workflow.yml@main
    with:
      blogger_client_id: hi
      blogger_client_secret: hello
      blogger_refresh_token: good
      blogger_blog_id: morning
#      blogger_client_id: ${{ secrets.BLOGGER_CLIENT_ID }}
#      blogger_client_secret: ${{ secrets.BLOGGER_CLIENT_SECRET }}
#      blogger_refresh_token: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
#      blogger_blog_id: ${{ secrets.BLOGGER_BLOG_ID }}