name: Test Secrets
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret (name only)
        run: |
          echo "BLOGGER_CLIENT_ID is set"
          echo "BLOGGER_CLIENT_SECRET is set"