name: MD2Blogger Reusable Workflow Caller

on:
  push:
    branches: [ main ]

jobs:
  call-md2blogger:
    uses: swellful-life/md2blogger/.github/workflows/workflow.yml@main
    with:
      github_token: ${{ inputs.github_token }}
      blogger_client_id: ${{ inputs.BLOGGER_CLIENT_ID }}
      blogger_client_secret: ${{ inputs.BLOGGER_CLIENT_SECRET }}
      blogger_refresh_token: ${{ inputs.BLOGGER_REFRESH_TOKEN }}
      blogger_blog_id: ${{ inputs.BLOGGER_BLOG_ID }}
