name: MD2Blogger Reusable Workflow Caller

on:
  push:
    branches: [ main ]

jobs:
  call-md2blogger:
    uses: swellful-life/md2blogger/.github/workflows/workflow.yml@main
    secrets:
      BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
      BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
      BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
      BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}